paycare: artifacts test report to repos - 10th commit

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -123,6 +123,14 @@ jobs:  # Ensemble des jobs du pipeline
                 path: ${{ env.ARTIFACT_DIR }}/reports/
                 if-no-files-found: ignore
             
+            # add the test report folder to the current git repository for inspection
+            - name: Upload Test reports to repository
+              uses: actions/upload-artifact@v4
+              with:
+                name: pytest-reports-repo
+                path: ${{ env.ARTIFACT_DIR }}/reports/
+                if-no-files-found: ignore
+            
             - name: Upload processed csv data
               uses: actions/upload-artifact@v4
               with:
@@ -130,24 +138,24 @@ jobs:  # Ensemble des jobs du pipeline
                 path: ${{ env.ARTIFACT_DIR }}/processed_data/
                 if-no-files-found: ignore
             
-            # # ===========================================================
-            # #  CLEANUP: Stop and remove the Docker container, and remove the Docker image to free up space.
-            # # ===========================================================
-            # - name: Stop Docker Container
-            #   if: always()
-            #   run: docker stop ${{ env.CONTAINER_NAME }} || true 
-            # # run: docker stop ${{ env.CONTAINER_NAME }}
+            # ===========================================================
+            #  CLEANUP: Stop and remove the Docker container, and remove the Docker image to free up space.
+            # ===========================================================
+            - name: Stop Docker Container
+              if: always()
+              run: docker stop ${{ env.CONTAINER_NAME }} || true 
+            # run: docker stop ${{ env.CONTAINER_NAME }}
             
-            # - name: remove docker container
-            #   if: always()
-            #   run: docker rm ${{ env.CONTAINER_NAME }}
+            - name: remove docker container
+              if: always()
+              run: docker rm ${{ env.CONTAINER_NAME }}
             
-            # - name: check docker container status
-            #   if: always()
-            #   run: |
-            #         docker ps -a
-            #         docker logs ${{ env.CONTAINER_NAME }}
+            - name: check docker container status
+              if: always()
+              run: |
+                    docker ps -a
+                    docker logs ${{ env.CONTAINER_NAME }}
             
-            # - name: remove docker image
-            #   if: always()
-            #   run: docker rmi ${{ env.IMAGE }}
+            - name: remove docker image
+              if: always()
+              run: docker rmi ${{ env.IMAGE }}
